using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace LittlePeeps
{
    // Pixel-snapped horizontal drag strip used by the build palette. The component lives on the
    // viewport, so it receives drags that start on a card as well as drags that start in a gap.
    // A drag suppresses the Button click generated by the same press.
    public class BuildPanelScroller : MonoBehaviour, IPointerDownHandler, IBeginDragHandler,
        IDragHandler, IEndDragHandler, IScrollHandler
    {
        [SerializeField] private RectTransform viewport;
        [SerializeField] private RectTransform content;
        // Gap held in front of the strip at either scroll stop. It has to clear the horizontal softness
        // of the viewport RectMask2D (12) plus the hover growth of a card (57 -> 69, so 6 per side), or
        // the outermost card fades into the mask while it rests against the stop.
        [SerializeField, Min(0f)] private float edgePadding = 18f;
        [SerializeField, Min(1f)] private float wheelStep = 24f;

        public bool IsDragging { get; private set; }
        public bool ShouldSuppressClick { get; private set; }

        private Canvas rootCanvas;
        private float minX;
        private float maxX;
        private readonly Vector3[] cardWorldCorners = new Vector3[4];

        private void Awake()
        {
            rootCanvas = GetComponentInParent<Canvas>();
            RefreshBounds();
        }

        private void OnEnable() => RefreshBounds();

        private void OnRectTransformDimensionsChange()
        {
            if (isActiveAndEnabled) RefreshBounds();
        }

        public void NotifyPointerDown()
        {
            ShouldSuppressClick = false;
        }

        // The strip always opens hard against the left stop, so the first card is whole at any resolution.
        // maxX is that stop by construction: content is anchored and pivoted to the left edge of the
        // viewport, so anchoredPosition.x is exactly the gap in front of the first card.
        public void ResetToStart()
        {
            RefreshBounds();
            SetContentX(maxX);
        }

        public bool CanHover(RectTransform cardRect)
        {
            if (viewport == null || cardRect == null) return true;

            // CalculateRelativeRectTransformBounds includes every active descendant. That makes the
            // hover test depend on the flying visual, shadow, and especially the very wide shine:
            // activating shine can push the calculated bounds outside the viewport, turn hover off,
            // hide shine, and repeat every frame. Use only the fixed layout/click slot's own corners.
            cardRect.GetWorldCorners(cardWorldCorners);
            float cardMinX = float.PositiveInfinity;
            float cardMaxX = float.NegativeInfinity;
            for (int i = 0; i < cardWorldCorners.Length; i++)
            {
                float localX = viewport.InverseTransformPoint(cardWorldCorners[i]).x;
                cardMinX = Mathf.Min(cardMinX, localX);
                cardMaxX = Mathf.Max(cardMaxX, localX);
            }

            Rect viewportRect = viewport.rect;
            const float pixelTolerance = 0.5f;
            return cardMinX >= viewportRect.xMin - pixelTolerance &&
                   cardMaxX <= viewportRect.xMax + pixelTolerance;
        }

        public void OnPointerDown(PointerEventData eventData) => NotifyPointerDown();

        public void OnBeginDrag(PointerEventData eventData)
        {
            IsDragging = true;
            ShouldSuppressClick = true;
        }

        public void OnDrag(PointerEventData eventData)
        {
            if (content == null) return;

            float scale = rootCanvas != null ? Mathf.Max(0.0001f, rootCanvas.scaleFactor) : 1f;
            SetContentX(content.anchoredPosition.x + eventData.delta.x / scale);
        }

        public void OnEndDrag(PointerEventData eventData)
        {
            IsDragging = false;
        }

        public void OnScroll(PointerEventData eventData)
        {
            if (content == null || Mathf.Approximately(eventData.scrollDelta.y, 0f)) return;
            ShouldSuppressClick = true;
            SetContentX(content.anchoredPosition.x + eventData.scrollDelta.y * wheelStep);
        }

        public void RefreshBounds()
        {
            if (viewport == null || content == null) return;

            LayoutRebuilder.ForceRebuildLayoutImmediate(content);
            float contentWidth = Mathf.Max(content.rect.width, LayoutUtility.GetPreferredWidth(content));
            float viewportWidth = viewport.rect.width;

            maxX = edgePadding;
            minX = Mathf.Min(maxX, viewportWidth - contentWidth - edgePadding);
            SetContentX(content.anchoredPosition.x);
        }

        private void SetContentX(float x)
        {
            if (content == null) return;
            Vector2 position = content.anchoredPosition;
            position.x = Mathf.Round(Mathf.Clamp(x, minX, maxX));
            position.y = Mathf.Round(position.y);
            content.anchoredPosition = position;
        }
    }
}
