using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

namespace LittlePeeps
{
    // Pixel-snapped horizontal drag strip used by the build palette. The component lives on the
    // viewport, so it receives drags that start on a card as well as drags that start in a gap.
    // A drag suppresses the Button click generated by the same press.
    public class BuildPanelScroller : MonoBehaviour, IPointerDownHandler, IBeginDragHandler,
        IDragHandler, IEndDragHandler, IScrollHandler
    {
        [SerializeField] private RectTransform viewport;
        [SerializeField] private RectTransform content;
        [SerializeField, Min(0f)] private float edgePadding = 8f;
        [SerializeField, Min(1f)] private float wheelStep = 24f;
        [SerializeField] private float initialPosition = -8f;

        public bool IsDragging { get; private set; }
        public bool ShouldSuppressClick { get; private set; }

        private Canvas rootCanvas;
        private float minX;
        private float maxX;

        private void Awake()
        {
            rootCanvas = GetComponentInParent<Canvas>();
            RefreshBounds();
        }

        private void OnEnable() => RefreshBounds();

        private void OnRectTransformDimensionsChange()
        {
            if (isActiveAndEnabled) RefreshBounds();
        }

        public void NotifyPointerDown()
        {
            ShouldSuppressClick = false;
        }

        public void ResetToInitialPosition()
        {
            RefreshBounds();
            SetContentX(initialPosition);
        }

        public bool CanHover(RectTransform cardRect)
        {
            if (viewport == null || cardRect == null) return true;

            Bounds cardBounds = RectTransformUtility.CalculateRelativeRectTransformBounds(viewport, cardRect);
            Rect viewportRect = viewport.rect;
            const float pixelTolerance = 0.5f;
            return cardBounds.min.x >= viewportRect.xMin - pixelTolerance &&
                   cardBounds.max.x <= viewportRect.xMax + pixelTolerance;
        }

        public void OnPointerDown(PointerEventData eventData) => NotifyPointerDown();

        public void OnBeginDrag(PointerEventData eventData)
        {
            IsDragging = true;
            ShouldSuppressClick = true;
        }

        public void OnDrag(PointerEventData eventData)
        {
            if (content == null) return;

            float scale = rootCanvas != null ? Mathf.Max(0.0001f, rootCanvas.scaleFactor) : 1f;
            SetContentX(content.anchoredPosition.x + eventData.delta.x / scale);
        }

        public void OnEndDrag(PointerEventData eventData)
        {
            IsDragging = false;
        }

        public void OnScroll(PointerEventData eventData)
        {
            if (content == null || Mathf.Approximately(eventData.scrollDelta.y, 0f)) return;
            ShouldSuppressClick = true;
            SetContentX(content.anchoredPosition.x + eventData.scrollDelta.y * wheelStep);
        }

        public void RefreshBounds()
        {
            if (viewport == null || content == null) return;

            LayoutRebuilder.ForceRebuildLayoutImmediate(content);
            float contentWidth = Mathf.Max(content.rect.width, LayoutUtility.GetPreferredWidth(content));
            float viewportWidth = viewport.rect.width;

            maxX = edgePadding;
            minX = Mathf.Min(maxX, viewportWidth - contentWidth - edgePadding);
            SetContentX(content.anchoredPosition.x);
        }

        private void SetContentX(float x)
        {
            if (content == null) return;
            Vector2 position = content.anchoredPosition;
            position.x = Mathf.Round(Mathf.Clamp(x, minX, maxX));
            position.y = Mathf.Round(position.y);
            content.anchoredPosition = position;
        }
    }
}
